# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    base_store:
        abstract:  true
        arguments: ['@doctrine.orm.entity_manager']

    employee_store:
        class: AppBundle\Base\EmployeeStore
        parent: base_store
